build := "{{artifact/id}}"

default:
    @just --list

clean:
    @-rm -rf public/static/js
    @-rm -rf public/static/css

release:
    @parallel -j2 --ctag --tag --lb just ::: release-cljs release-css

watch:
    @parallel -j2 --ctag --tag --lb just ::: watch-cljs watch-css

test:
    @npx shadow-cljs compile ci
    @npx karma start --single-run

lint:
    @clj-kondo --parallel --lint src test

preview: release
    @npx http-server

build-report:
    @npx shadow-cljs run shadow.cljs.build-report {{ build }} report.html

release-cljs:
    @npx shadow-cljs release {{ build }}

watch-cljs:
    @npx shadow-cljs watch {{ build }}

release-css:
    @clojure -X:girouette-processor
    @npx postcss -r public/static/css/main.css

watch-css:
    @clojure -X:girouette-processor :watch? true
