#!/usr/bin/env bash
#MISE description="Serve production JS and CSS in a local webserver"
#MISE depends=["release"]

set -o nounset
set -o errexit
set -o pipefail

preview () {
    npx http-server
}

preview
