#!/usr/bin/env bash
#MISE description="Generate production JS"
#MISE sources=["deps.edn", "package-lock.json", "shadow-cljs.edn", "src/**/*.cljs"]
#MISE outputs=["public/static/js/{{artifact/id}}.js"]

set -o nounset
set -o errexit
set -o pipefail

release () {
    npx shadow-cljs release {{artifact/id}}
}

release
