#!/usr/bin/env bash
# mise description="Generate production CSS"
# mise sources=["deps.edn", "package-lock.json", "src/**/*.cljs", "static/css/main.css"]
# mise outputs=["public/static/css/main.css"]

set -o nounset
set -o errexit
set -o pipefail

release () {
    npx postcss static/css/main.css -o public/static/css/main.css
}

release
