#!/usr/bin/env bash
#MISE description="Generate production CSS"
#MISE sources=["deps.edn", "package-lock.json", "src/**/*.cljs", "static/css/main.css"]
#MISE outputs=["public/static/css/main.css"]

set -o nounset
set -o errexit
set -o pipefail

release () {
    npx postcss static/css/main.css -o public/static/css/main.css
}

release
