version: "3"

silent: true

vars:
  BUILD: "{{artifact/id}}"

tasks:
  default:
    cmds:
      - task --list

  clean:
    desc: Remove generated JS and CSS
    deps:
      - cljs:clean
      - css:clean

  release:
    desc: Generate production JS and CSS
    deps:
      - cljs:release
      - css:release

  watch:
    desc: Watch source files and generate development JS and CSS
    deps:
      - cljs:watch
      - css:watch

  lint:
    desc: Lint code using clj-kondo
    cmds:
      - rg -tclojure -tedn --files | xargs clj-kondo --parallel --lint

  preview:
    desc: Serve production JS and CSS in a local webserver
    deps: [release]
    cmds:
      - npx http-server

  build-report:
    desc: Generate shadow-cljs build report
    cmds:
      - npx shadow-cljs run shadow.cljs.build-report {{.BUILD}} report.html

  cljs:release:
    desc: Generate production JS
    cmds:
      - npx shadow-cljs release {{.BUILD}}

  cljs:watch:
    desc: Watch source files and generate development JS
    cmds:
      - npx shadow-cljs watch {{.BUILD}}

  cljs:clean:
    desc: Remove generated JS
    cmds:
      - rm -rf public/static/js

  css:release:
    desc: Generate production CSS
    cmds:
      - clojure -X:girouette-processor
      - npx postcss -r public/static/css/main.css

  css:watch:
    desc: Watch source files and generate development CSS
    cmds:
      - clojure -X:girouette-processor :watch? true

  css:clean:
    desc: Remove generated CSS
    cmds:
      - rm -rf public/static/css
