version: "3"

silent: true

vars:
  BUILD: "{{artifact/id}}"

tasks:
  default:
    cmd: task --list

  clean:
    desc: Remove generated JS and CSS
    deps:
      - cljs:clean
      - css:clean

  test:
    desc: Run unit tests
    cmds:
      - npx shadow-cljs compile ci
      - npx karma start --single-run

  release:
    desc: Generate production JS and CSS
    deps:
      - cljs:release
      - css:release

  watch:
    desc: Watch source files and generate development JS and CSS
    deps:
      - cljs:watch
      - css:watch

  lint:
    desc: Lint code using clj-kondo
    cmd: rg -tclojure -tedn --files | xargs clj-kondo --parallel --lint

  preview:
    desc: Serve production JS and CSS in a local webserver
    deps: [release]
    cmd: npx http-server

  report:
    desc: Generate shadow-cljs build report
    cmd: npx shadow-cljs run shadow.cljs.build-report {{.BUILD}} report.html

  cljs:clean:
    desc: Remove generated JS
    cmd: rm -rf public/static/js

  cljs:release:
    desc: Generate production JS
    cmd: npx shadow-cljs release {{.BUILD}}
    sources:
      - deps.edn
      - package-lock.json
      - shadow-cljs.edn
      - src/**/*.cljs
    generates:
      - public/static/js/{{.BUILD}}.js

  cljs:watch:
    desc: Watch source files and generate development JS
    cmd: npx shadow-cljs watch {{.BUILD}}

  css:clean:
    desc: Remove generated CSS
    cmd: rm -rf public/static/css

  css:release:
    desc: Generate production CSS
    cmds:
      - npx postcss static/css/main.css -o public/static/css/main.css
    sources:
      - deps.edn
      - package-lock.edn
      - src/**/*.cljs
      - static/css/main.css
    generates:
      - public/static/css/main.css

  css:watch:
    desc: Watch source files and generate development CSS
    cmd: npx postcss static/css/main.css -w -o public/static/css/main.css --verbose
